/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestcopyRouteImport } from './routes/test copy'
import { Route as TestRouteImport } from './routes/test'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as MyHighwayRouteImport } from './routes/my-highway'
import { Route as MyEventsRouteImport } from './routes/my-events'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GarageRouteImport } from './routes/garage'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as Dash2RouteImport } from './routes/dash2'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EventSlugIdRouteImport } from './routes/event.$slugId'
import { Route as ApiUploadRouteImport } from './routes/api.upload'
import { Route as ApiSeedRouteImport } from './routes/api.seed'
import { Route as ApiImagesRouteImport } from './routes/api.images'
import { Route as ApiHealthRouteImport } from './routes/api.health'
import { Route as ApiImagesIdRouteImport } from './routes/api.images.$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api.auth.$'

const TestcopyRoute = TestcopyRouteImport.update({
  id: '/test copy',
  path: '/test copy',
  getParentRoute: () => rootRouteImport,
} as any)
const TestRoute = TestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const MyHighwayRoute = MyHighwayRouteImport.update({
  id: '/my-highway',
  path: '/my-highway',
  getParentRoute: () => rootRouteImport,
} as any)
const MyEventsRoute = MyEventsRouteImport.update({
  id: '/my-events',
  path: '/my-events',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GarageRoute = GarageRouteImport.update({
  id: '/garage',
  path: '/garage',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const Dash2Route = Dash2RouteImport.update({
  id: '/dash2',
  path: '/dash2',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventSlugIdRoute = EventSlugIdRouteImport.update({
  id: '/event/$slugId',
  path: '/event/$slugId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadRoute = ApiUploadRouteImport.update({
  id: '/api/upload',
  path: '/api/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSeedRoute = ApiSeedRouteImport.update({
  id: '/api/seed',
  path: '/api/seed',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImagesRoute = ApiImagesRouteImport.update({
  id: '/api/images',
  path: '/api/images',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImagesIdRoute = ApiImagesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiImagesRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dash2': typeof Dash2Route
  '/dashboard': typeof DashboardRoute
  '/explore': typeof ExploreRoute
  '/garage': typeof GarageRoute
  '/login': typeof LoginRoute
  '/my-events': typeof MyEventsRoute
  '/my-highway': typeof MyHighwayRoute
  '/settings': typeof SettingsRoute
  '/test': typeof TestRoute
  '/test copy': typeof TestcopyRoute
  '/api/health': typeof ApiHealthRoute
  '/api/images': typeof ApiImagesRouteWithChildren
  '/api/seed': typeof ApiSeedRoute
  '/api/upload': typeof ApiUploadRoute
  '/event/$slugId': typeof EventSlugIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/images/$id': typeof ApiImagesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dash2': typeof Dash2Route
  '/dashboard': typeof DashboardRoute
  '/explore': typeof ExploreRoute
  '/garage': typeof GarageRoute
  '/login': typeof LoginRoute
  '/my-events': typeof MyEventsRoute
  '/my-highway': typeof MyHighwayRoute
  '/settings': typeof SettingsRoute
  '/test': typeof TestRoute
  '/test copy': typeof TestcopyRoute
  '/api/health': typeof ApiHealthRoute
  '/api/images': typeof ApiImagesRouteWithChildren
  '/api/seed': typeof ApiSeedRoute
  '/api/upload': typeof ApiUploadRoute
  '/event/$slugId': typeof EventSlugIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/images/$id': typeof ApiImagesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dash2': typeof Dash2Route
  '/dashboard': typeof DashboardRoute
  '/explore': typeof ExploreRoute
  '/garage': typeof GarageRoute
  '/login': typeof LoginRoute
  '/my-events': typeof MyEventsRoute
  '/my-highway': typeof MyHighwayRoute
  '/settings': typeof SettingsRoute
  '/test': typeof TestRoute
  '/test copy': typeof TestcopyRoute
  '/api/health': typeof ApiHealthRoute
  '/api/images': typeof ApiImagesRouteWithChildren
  '/api/seed': typeof ApiSeedRoute
  '/api/upload': typeof ApiUploadRoute
  '/event/$slugId': typeof EventSlugIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/images/$id': typeof ApiImagesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dash2'
    | '/dashboard'
    | '/explore'
    | '/garage'
    | '/login'
    | '/my-events'
    | '/my-highway'
    | '/settings'
    | '/test'
    | '/test copy'
    | '/api/health'
    | '/api/images'
    | '/api/seed'
    | '/api/upload'
    | '/event/$slugId'
    | '/api/auth/$'
    | '/api/images/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/dash2'
    | '/dashboard'
    | '/explore'
    | '/garage'
    | '/login'
    | '/my-events'
    | '/my-highway'
    | '/settings'
    | '/test'
    | '/test copy'
    | '/api/health'
    | '/api/images'
    | '/api/seed'
    | '/api/upload'
    | '/event/$slugId'
    | '/api/auth/$'
    | '/api/images/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/dash2'
    | '/dashboard'
    | '/explore'
    | '/garage'
    | '/login'
    | '/my-events'
    | '/my-highway'
    | '/settings'
    | '/test'
    | '/test copy'
    | '/api/health'
    | '/api/images'
    | '/api/seed'
    | '/api/upload'
    | '/event/$slugId'
    | '/api/auth/$'
    | '/api/images/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  Dash2Route: typeof Dash2Route
  DashboardRoute: typeof DashboardRoute
  ExploreRoute: typeof ExploreRoute
  GarageRoute: typeof GarageRoute
  LoginRoute: typeof LoginRoute
  MyEventsRoute: typeof MyEventsRoute
  MyHighwayRoute: typeof MyHighwayRoute
  SettingsRoute: typeof SettingsRoute
  TestRoute: typeof TestRoute
  TestcopyRoute: typeof TestcopyRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiImagesRoute: typeof ApiImagesRouteWithChildren
  ApiSeedRoute: typeof ApiSeedRoute
  ApiUploadRoute: typeof ApiUploadRoute
  EventSlugIdRoute: typeof EventSlugIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test copy': {
      id: '/test copy'
      path: '/test copy'
      fullPath: '/test copy'
      preLoaderRoute: typeof TestcopyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-highway': {
      id: '/my-highway'
      path: '/my-highway'
      fullPath: '/my-highway'
      preLoaderRoute: typeof MyHighwayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-events': {
      id: '/my-events'
      path: '/my-events'
      fullPath: '/my-events'
      preLoaderRoute: typeof MyEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/garage': {
      id: '/garage'
      path: '/garage'
      fullPath: '/garage'
      preLoaderRoute: typeof GarageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dash2': {
      id: '/dash2'
      path: '/dash2'
      fullPath: '/dash2'
      preLoaderRoute: typeof Dash2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event/$slugId': {
      id: '/event/$slugId'
      path: '/event/$slugId'
      fullPath: '/event/$slugId'
      preLoaderRoute: typeof EventSlugIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload': {
      id: '/api/upload'
      path: '/api/upload'
      fullPath: '/api/upload'
      preLoaderRoute: typeof ApiUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/seed': {
      id: '/api/seed'
      path: '/api/seed'
      fullPath: '/api/seed'
      preLoaderRoute: typeof ApiSeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/images': {
      id: '/api/images'
      path: '/api/images'
      fullPath: '/api/images'
      preLoaderRoute: typeof ApiImagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/images/$id': {
      id: '/api/images/$id'
      path: '/$id'
      fullPath: '/api/images/$id'
      preLoaderRoute: typeof ApiImagesIdRouteImport
      parentRoute: typeof ApiImagesRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ApiImagesRouteChildren {
  ApiImagesIdRoute: typeof ApiImagesIdRoute
}

const ApiImagesRouteChildren: ApiImagesRouteChildren = {
  ApiImagesIdRoute: ApiImagesIdRoute,
}

const ApiImagesRouteWithChildren = ApiImagesRoute._addFileChildren(
  ApiImagesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  Dash2Route: Dash2Route,
  DashboardRoute: DashboardRoute,
  ExploreRoute: ExploreRoute,
  GarageRoute: GarageRoute,
  LoginRoute: LoginRoute,
  MyEventsRoute: MyEventsRoute,
  MyHighwayRoute: MyHighwayRoute,
  SettingsRoute: SettingsRoute,
  TestRoute: TestRoute,
  TestcopyRoute: TestcopyRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiImagesRoute: ApiImagesRouteWithChildren,
  ApiSeedRoute: ApiSeedRoute,
  ApiUploadRoute: ApiUploadRoute,
  EventSlugIdRoute: EventSlugIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.jsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
